# -*- coding: utf-8 -*-
"""HOA 0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-XVuw1ioO71gwWmqwpG0_09ntx4wIhb0
"""

class Node:
  def __init__(self, newData, right = None ):
    self.data = newData
    self.nextNode = right

  def print(self):
   currentNode = self
   print(currentNode.head)
   while currentNode != None:
    currentNode = self.addNode(self.next)


  def addNode(self, newNode):
    self.nextNode = newNode
    self.newNode = secondNode
    self.newNode = thirdNode
    self.newNode == None

  def deleteNode(self):
    pass

root = Node('C')
secondNode = Node('P')
thirdNode = Node('E')

print(root, secondNode, thirdNode)