# -*- coding: utf-8 -*-
"""RiddleGame_Adornado_Cabacungan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-HTr_2XcIW53NSgwvNNCiAp22r7s8CM5
"""

class Character:
    def __init__(self, name):
        self.name = name
        self.side = "LEFT"

    def move(self, farmer):
        if self.side == "LEFT":
            self.side = "RIGHT"
        else:
            self.side = "LEFT"
        print(f"The {self.name} moved to the {self.side} side of the river")

class Farmer(Character):
    def __init__(self):
        Character.__init__(self, "Farmer")


class Wolf(Character):
    def __init__(self):
        Character.__init__(self, "Wolf")


class Sheep(Character):
    def __init__(self):
        Character.__init__(self, "Sheep")


class Cabbage(Character):
    def __init__(self):
        Character.__init__(self, "Cabbage")


class Project:
    def __init__(self):
        self.farmer = Farmer()
        self.wolf = Wolf()
        self.sheep = Sheep()
        self.cabbage = Cabbage()
        self.characters = {"w": self.wolf, "s": self.sheep, "c": self.cabbage}
        self.none = False

    def side(self):
        print("-------------------------------------------------------------")
        print(" Farmer:", self.farmer.side)
        print(" Wolf:", self.wolf.side)
        print(" Sheep:", self.sheep.side)
        print(" Cabbage:", self.cabbage.side)
        print("-------------------------------------------------------------")

    def play(self):
        print("Riddle Game!", "\n")
        print("A farmer with a wolf, a sheep, and a cabbage must cross a river by boat.\nThe boat can only carry the farmer and a single passenger.")
        print("If left unattended together, the wolf would eat the sheep,\nor the sheep would eat the cabbage.")
        print("How can they cross the river without anything being eaten?")

        self.side()

        while True:
            if self.none:
                print("Press 'w' for Wolf, 's' for Sheep, 'c' for Cabbage, or 'n' for None.")
            else:
                print("Press 'w' for Wolf, 's' for Sheep, or 'c' for Cabbage.")

            ui = input("What should the farmer bring? ").lower()
            print("-------------------------------------------------------------")

            if ui == "n" and self.none:
                self.farmer.move(self.farmer)
                print(" ")
                self.side()

                if (self.wolf.side == self.sheep.side and self.farmer.side != self.wolf.side) or (
                        self.sheep.side == self.cabbage.side and self.farmer.side != self.sheep.side):
                    print(f"You lose! The {self.wolf.name} ate the {self.sheep.name}." if self.wolf.side == self.sheep.side
                          else f"You lose! The {self.sheep.name} ate the {self.cabbage.name}.")
                    return

            elif ui in self.characters:
                character = self.characters[ui]
                character.move(self.farmer)
                self.farmer.move(self.farmer)

                self.side()

                if (self.wolf.side == self.sheep.side and self.farmer.side != self.wolf.side) or (
                        self.sheep.side == self.cabbage.side and self.farmer.side != self.sheep.side):
                    print(f"You lose! The {self.wolf.name} ate the {self.sheep.name}." if self.wolf.side == self.sheep.side
                          else f"You lose! The {self.sheep.name} ate the {self.cabbage.name}.")
                    return

                if all(character.side == "RIGHT" for character in [self.farmer, self.wolf, self.sheep, self.cabbage]):
                    print("Congratulations! The farmer, sheep, wolf, and cabbage arrived safely on the other side of the river")
                    break
            else:
                print("Invalid input. Please press 'w' for Wolf, 's' for Sheep, 'c' for Cabbage, or 'n' for None.")
                continue

            self.none = True


if __name__ == "__main__":
    game = Project()
    game.play()